.PHONY: init
init:
	@terraform init

.PHONY: plan
plan:
	@terraform plan

.PHONY: apply
apply:
	@terraform apply

.PHONY: apply-yes
apply-yes:
	@terraform apply -auto-approve

.PHONY: destroy-yes
destroy-yes:
	@terraform destroy -auto-approve
